version: '3.1'

services:


  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "443:443"
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=$EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "traefik_letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=$WHITELIST"

  erigon-eth:
    container_name: erigon-eth
    build:
      args:
        ERIGON_VERSION: v2.37.0
      context: ./erigon-make
      dockerfile: Dockerfile
    image: erigon/erigon:v2.37.0
    volumes:
      - "erigon:/datadir"
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    restart: unless-stopped
    stop_grace_period: 1m
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.erigon-eth-stripprefix.stripprefix.prefixes=/eth-archive"
      - "traefik.http.services.erigon-eth.loadbalancer.server.port=8545"
      - "traefik.http.routers.erigon-eth.entrypoints=websecure"
      - "traefik.http.routers.erigon-eth.tls.certresolver=myresolver"
      - "traefik.http.routers.erigon-eth.rule=Host(`$DOMAIN`) && PathPrefix(`/eth-archive`)"
      - "traefik.http.routers.erigon-eth.middlewares=erigon-polygon-stripprefix, ipwhitelist"


volumes:
    erigon:
    traefik_letsencrypt:
